version: 2.1

workflows:
  deploy:
    jobs:
      - build_docker_images:
          filters:
            branches:
              only: deployment

      - deploy:
          requires:
            - build_docker_images
          filters:
            branches:
              only: deployment

jobs:
  build_docker_images:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to github container registry
          command: |
            echo $GITHUB_TOKEN | docker login ghcr.io -u $CIRCLE_PROJECT_USERNAME --password-stdin

      - run:
          name: Build and push frontend image
          command: |
            docker build -t ghcr.io/lukazuljevic/drawing_recognition_ai_frontend:${CIRCLE_SHA1} -t ghcr.io/lukazuljevic/drawing_recognition_ai_frontend:deployment ./frontend
            docker push ghcr.io/lukazuljevic/drawing_recognition_ai_frontend:${CIRCLE_SHA1}
            docker push ghcr.io/lukazuljevic/drawing_recognition_ai_frontend:deployment

      - run:
          name: Build and push model image
          command: |
            docker build -t ghcr.io/lukazuljevic/drawing_recognition_ai_model:${CIRCLE_SHA1} -t ghcr.io/lukazuljevic/drawing_recognition_ai_model:deployment ./model
            docker push ghcr.io/lukazuljevic/drawing_recognition_ai_model:${CIRCLE_SHA1}
            docker push ghcr.io/lukazuljevic/drawing_recognition_ai_model:deployment

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "9f:b1:e5:7f:a9:d5:fe:72:60:33:7a:0e:4c:14:23:87"

      - run:
          name: Copy docker-compose.yml to remote server
          command: |
            scp -o StrictHostKeyChecking=no docker-compose.yml $SSH_USER@$SSH_HOST:/home/$SSH_USER/docker-compose.yml

      - run:
          name: SSH into remote server and deploy to server
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \<< EOF
              echo $GITHUB_TOKEN | docker login ghcr.io -u $CIRCLE_PROJECT_USERNAME --password-stdin

              sudo docker pull ghcr.io/lukazuljevic/drawing_recognition_ai_frontend:deployment
              sudo docker pull ghcr.io/lukazuljevic/drawing_recognition_ai_model:deployment

              sudo docker-compose down || true
              sudo docker-compose up -d

              sudo docker image prune -f
            EOF
