version: 2.1

workflows:
  deploy:
    jobs:
      - build_docker_images:
          filters:
            branches:
              only: deployment

jobs:
  build_docker_images:
    docker:
      - image: cimg/node:20-slim
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to github container registry
          command: |
            echo $GITHUB_TOKEN | docker login ghcr.io -u $CIRCLE_PROJECT_USERNAME --password-stdin

      - run:
          name: Build and push frontend image
          command: |
            docker build -t ghcr.io/LukaZuljevic/drawing_recognition_ai_frontend:${CIRCLE_SHA1} -t ghcr.io/LukaZuljevic/drawing_recognition_ai_frontend:deployment ./frontend
            docker push ghcr.io/LukaZuljevic/drawing_recognition_ai_frontend:${CIRCLE_SHA1}
            docker push ghcr.io/LukaZuljevic/drawing_recognition_ai_frontend:deployment

      - run:
          name: Build and push model image
          command: |
            docker build -t ghcr.io/LukaZuljevic/drawing_recognition_ai_model:${CIRCLE_SHA1} -t ghcr.io/LukaZuljevic/drawing_recognition_ai_model:deployment ./model
            docker push ghcr.io/LukaZuljevic/drawing_recognition_ai_model:${CIRCLE_SHA1}
            docker push ghcr.io/LukaZuljevic/drawing_recognition_ai_model:deployment
