---
- hosts: web
  become: true
  gather_facts: true
  vars_files:
    - ../vars/deployment.yml
  remote_user: admin

  pre_tasks:
    - name: Clear apt cache
      apt:
        update_cache: yes
        cache_valid_time: 7200
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - admin
          - test
    - role: nginx
    - role: model

  tasks:
    - name: Print all gathered facts
      debug:
        var: ansible_facts
