- hosts: localhost
  gather_facts: true
  become: true  
  # remote_user: admin

  # pre_tasks:
  #   - name: Clear apt cache
  #     apt:
  #       update_cache: yes
  #       cache_valid_time: 7200
  
  roles:
    - role: nginx

  tasks:
    - name: Print all gathered facts
      debug:
        var: ansible_facts