plugin: aws_ec2
profile: lukaZuljevic

regions:
  - eu-central-1

hostnames:
  - ip-address

filters:
  tag:Name: drawing_recognition_ai

#referenciras se na "web" u ovom slucaju kad budes koristio sa playbook-om
keyed_groups:
  - key: tags.Role
